## other configuration excluded from example...
exclude_patterns:
  # Defaults
  - 'config/'
  - 'db/'
  - 'dist/'
  - 'features/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - 'Tests/'
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
  # Custom
  - '**/__tests__/'
  - 'src/@generated/'
  - 'src/@types/'
